import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/ui/header'
import Footer from '@/app/ui/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-center items-center`} style={{minHeight: '100vh'}}>
        <Header></Header>
        <div className='flex-grow-1'>
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  )
}
